package de.isibboi.agentsim.game.entities.buildings;

import de.isibboi.agentsim.game.EntityLocationManager;
import de.isibboi.agentsim.game.entities.Entity;
import de.isibboi.agentsim.game.entities.MapEntity;
import de.isibboi.agentsim.game.entities.ai.intends.Intend;

/**
 * The base class for the buildings.
 * Buildings can give orders to the swarm entities or interact in other special ways.
 * They also might provide some information to the entities.
 * 
 * @author Sebastian Schmidt
 * @since 0.3.0
 *
 */
public abstract class Building extends MapEntity {
	/**
	 * Creates a new object.
	 * 
	 * @param entityLocationManager The entity location manager.
	 */
	public Building(final EntityLocationManager entityLocationManager) {
		super(entityLocationManager);
	}

	@Override
	public void collideWith(final Entity entity, final int tick) {
		// Let other entities handle the collision.
		entity.collideWith(this, tick);
	}

	/**
	 * Returns the intends created by this building with their respective priority.
	 * A building ensures that its purpose is fulfilled by giving intends to goblins.
	 * @param tick The current tick.
	 * @return The intends generated by this building.
	 */
	public abstract Iterable<? extends Intend> getIntends(final int tick);
}