package de.isibboi.agentsim.ui.event;

import java.util.Objects;

/**
 * An event that represents user input.
 * 
 * @author Sebastian Schmidt
 * @since 0.3.0
 */
public class UserActionEvent {
	private final Object _source;

	/**
	 * Creates a new {@link UserActionEvent} generated by the given component.
	 * @param source the component that generated this event.
	 */
	public UserActionEvent(final Object source) {
		Objects.requireNonNull(source, "'source' must not be null.");

		_source = source;
	}

	/**
	 * @return the component that generated this event.
	 */
	public Object getSource() {
		return _source;
	}
}
