package de.isibboi.agentsim.ui.event;

import de.isibboi.agentsim.ui.component.UIComponent;

/**
 * An event that represents user input.
 * 
 * @author Sebastian Schmidt
 * @since 0.3.0
 */
public class UserActionEvent {
	private final UIComponent _source;
	
	/**
	 * Creates a new {@link UserActionEvent} generated by the given component.
	 * @param source the component that generated this event.
	 */
	public UserActionEvent(final UIComponent source) {
		_source = source;
	}

	/**
	 * @return the component that generated this event.
	 */
	public UIComponent getSource() {
		return _source;
	}
}
